server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: http://localhost:8081
          predicates:
            - Path=/events/**

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
